#!/bin/bash

dotfiles_dir=~/dotfiles
dotfiles_bak=~/dotfiles_bak
files="bash/.bashrc bash/.bash_profile"

echo "Creating $dotfiles_bak for backup of existing dotfiles in ~"
mkdir -p $dotfiles_bak

mv ~/.bashrc $dotfiles_bak
ln -s $dotfiles_dir/bash/.bashrc ~/.bashrc

mv ~/.bash_profile $dotfiles_bak
ln -s $dotfiles_dir/bash/.bash_profile ~/.bash_profile
