add_newline = true
palette = "catppuccin_mocha"

[directory]
truncation_length = 4
truncate_to_repo = false
style = "bold blue"

[git_branch]
style = "bold mauve"

[git_status]
disabled = false
style = "bold peach"

[cmd_duration]
min_time = 2000
style = "bold yellow"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
overlay0  = "#6c7086"
surface0  = "#313244"
base      = "#1e1e2e"
